# Laboratorio 3 Numpy y Pandas
### Ciencia de Datos en Python
### Seccion V
### 17001393
### Pablo Daniel Passarelli López

### Imports

In [1]:
import numpy as np

### 1)

In [6]:
arr = np.array([])
for i in range(0, 1000):
	arr = np.append(arr, False)

print(f'Tamaño: {arr.nbytes}')

Tamaño: 8000


### 2)

In [20]:
arr = np.array([])
for i in range(0, 100):
	esPar = ((i + 1) % 2) == 0

	if (esPar):
		arr = np.append(arr, i+1)
arr

array([  2.,   4.,   6.,   8.,  10.,  12.,  14.,  16.,  18.,  20.,  22.,
        24.,  26.,  28.,  30.,  32.,  34.,  36.,  38.,  40.,  42.,  44.,
        46.,  48.,  50.,  52.,  54.,  56.,  58.,  60.,  62.,  64.,  66.,
        68.,  70.,  72.,  74.,  76.,  78.,  80.,  82.,  84.,  86.,  88.,
        90.,  92.,  94.,  96.,  98., 100.])

### 3) Pendiente

In [32]:
matriz = np.array([
	[2,4,5,6],
  [0,3,7,4],
  [8,8,5,2],
  [1,5,6,1]
])

# def encontrarSubArr(matriz, subarray_buscado):
# 	indices_filas, = np.where((matriz == subarray_buscado).all(axis=1))

# 	if len(indices_filas) > 0:
# 		posicion = indices_filas[0]
# 		return matriz[posicion]
# 	else:
# 		return 'No existe'


# arr = np.array([0,3,7,4])
# print(encontrarSubArr(matriz, arr))

# arr = np.array([2,5])
# print(encontrarSubArr(matriz, arr))
matriz

array([[2, 4, 5, 6],
       [0, 3, 7, 4],
       [8, 8, 5, 2],
       [1, 5, 6, 1]])

### 4)

In [30]:
a = np.array([1,4,2,7])
b = np.array([1,3,2,9])
print(np.mean(a - b))

[ 0  1  0 -2]
-0.25


### 5)

In [37]:
arr = np.array([
		[1.33, 4.5],
		[30, 10.7],
		[70.2, 0.5]
])

arr = np.concatenate((arr, [[37.1, -3.6]]))

# arr = np.append(arr, [37.1, -3.6])

arr

array([[ 1.33,  4.5 ],
       [30.  , 10.7 ],
       [70.2 ,  0.5 ],
       [37.1 , -3.6 ]])

### 6)

In [38]:
arr = np.transpose(arr)

arr

array([[ 1.33, 30.  , 70.2 , 37.1 ],
       [ 4.5 , 10.7 ,  0.5 , -3.6 ]])

## Parte 2

In [41]:
import pandas as pd

### 1)

In [45]:
datos = pd.read_csv('NucleosPoblacion.csv', delimiter=',')

datos

FID  OBJECTID                           Texto  Poblacion  CodMun  \
0      0         1                         Agüimes    29431.0   35002   
1      1         2                         Antigua    10458.0   35003   
2      2         3                        Arrecife    58156.0   35004   
3      3         4                          Arucas    36745.0   35006   
4      4         5                          Gáldar    24473.0   35009   
..   ...       ...                             ...        ...     ...   
847  847       848             Infante Juan Manuel    14192.0   30030   
848  848       849           Santa Maria de Gracia    13349.0   30030   
849  849       850                    Vista Alegre    15208.0   30030   
850  850       851  Poligono Sta M de Benquerencia    19177.0   45168   
851  851       852                            Grao    16367.0   12040   

                                      Municipio  CodProvin  \
0                                       Agüimes         35   
1                                       Antigua         35   
2                                      Arrecife         35   
3                                        Arucas         35   
4                                        Gáldar         35   
..                                          ...        ...   
847                                      Murcia         30   
848                                      Murcia         30   
849                                      Murcia         30   
850                                      Toledo         45   
851  Castellón de la Plana/Castelló de la Plana         12   

              Provincia          X          Y  
0            Las Palmas -15.446012  27.900542  
1            Las Palmas -14.013301  28.418966  
2            Las Palmas -13.551451  28.960649  
3            Las Palmas -15.521512  28.117496  
4            Las Palmas -15.654111  28.143873  
..                  ...        ...        ...  
847              Murcia  -1.124304  37.979033  
848              Murcia  -1.202069  37.984024  
849              Murcia  -1.130564  37.995715  
850              Toledo  -3.948364  39.866699  
851  Castelló/Castellón   0.012911  39.973568  

[852 rows x 10 columns]